---

- hosts: all
  become: true
  tasks:

  - name: update repository index Debian
    apt:
      update_cache: yes
    when: ansible_distribution in ["Debian", "Ubuntu"]

  - name: install apache2, php packages Debian
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Debian"

  - name: update repository index CentOS
    dnf:
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install httpd, php packages CentOS
    dnf:
      name: 
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"
